package globutil

import "testing"

// Code generated by scripts/genGitignoreParityTest.js. DO NOT EDIT.
//
// Ground truth for .gitignore parity. Every expectation was produced by running the real
// `git check-ignore` (git version 2.39.5) over a fixed file tree, one .gitignore per case. git is
// used as an oracle, so no test data is copied from git's own GPL-licensed test suite.
//
// A case lists the paths git ignores; every other path in gitignoreParityPaths must NOT
// match, so each case asserts over the whole corpus rather than only the positives.

var gitignoreParityPaths = []string{
	"readme.md",
	"server.log",
	"a.ts",
	"a.tsx",
	"a.d.ts",
	"useThing.ts",
	"Button.stories.tsx",
	"foo.test.ts",
	"index.ts",
	".hidden.ts",
	"file-name.ts",
	"boot",
	"logs/error.log",
	"logs/deep/error.log",
	"build-out/a.js",
	"node_modules/react/index.js",
	"src/index.ts",
	"src/a.ts",
	"src/a.tsx",
	"src/useThing.ts",
	"src/Button.stories.tsx",
	"src/foo.test.ts",
	"src/a.d.ts",
	"src/cache-x/f.ts",
	"src/vendor/lib.ts",
	"src/nested/index.ts",
	"src/nested/deep/index.ts",
	"src/nested/deep/a.ts",
	"src/pages/index.tsx",
	"src/pages/admin/dash.tsx",
	"src/useSearch/common.ts",
	"src/__tests__/a.ts",
	"src/components/Button.ts",
	"a/c.ts",
	"a/b/c.ts",
	"a/x/b/c.ts",
	"a/x/y/b/z/c.ts",
	"mm/b",
	"mm/x/b",
	"mm/x/y/b",
	"dist/app.js",
	"dist/manifest.json",
	"dist/public/app.js",
	"deep/nested/x.log",
	"deep/nested/c.ts",
	"pkg/node_modules/x/i.js",
	"docs/readme.md",
	"sub/boot",
	"sub/dist/app.js",
	"src/!bang.ts",
	"logs/important/b.log",
	"build/x.js",
	"build/keep/y.js",
}

type gitignoreParityCase struct {
	patterns []string
	desc     string
	matches  []string // paths git ignores; all others must not match
}

var gitignoreParityCases = []gitignoreParityCase{
	{patterns: []string{"readme.md"}, matches: []string{"docs/readme.md", "readme.md"}},
	{patterns: []string{"dist"}, matches: []string{"dist/app.js", "dist/manifest.json", "dist/public/app.js", "sub/dist/app.js"}},
	{patterns: []string{"boot"}, matches: []string{"boot", "sub/boot"}},
	{patterns: []string{"/boot"}, matches: []string{"boot"}},
	{patterns: []string{"node_modules"}, matches: []string{"node_modules/react/index.js", "pkg/node_modules/x/i.js"}},
	{patterns: []string{"index.ts"}, matches: []string{"index.ts", "src/index.ts", "src/nested/deep/index.ts", "src/nested/index.ts"}},
	{patterns: []string{"*.log"}, matches: []string{"deep/nested/x.log", "logs/deep/error.log", "logs/error.log", "logs/important/b.log", "server.log"}},
	{patterns: []string{"*.ts"}, matches: []string{".hidden.ts", "a.d.ts", "a.ts", "a/b/c.ts", "a/c.ts", "a/x/b/c.ts", "a/x/y/b/z/c.ts", "deep/nested/c.ts", "file-name.ts", "foo.test.ts", "index.ts", "src/!bang.ts", "src/__tests__/a.ts", "src/a.d.ts", "src/a.ts", "src/cache-x/f.ts", "src/components/Button.ts", "src/foo.test.ts", "src/index.ts", "src/nested/deep/a.ts", "src/nested/deep/index.ts", "src/nested/index.ts", "src/useSearch/common.ts", "src/useThing.ts", "src/vendor/lib.ts", "useThing.ts"}},
	{patterns: []string{"*.tsx"}, matches: []string{"Button.stories.tsx", "a.tsx", "src/Button.stories.tsx", "src/a.tsx", "src/pages/admin/dash.tsx", "src/pages/index.tsx"}},
	{patterns: []string{"use*.ts"}, matches: []string{"src/useThing.ts", "useThing.ts"}},
	{patterns: []string{"log*"}, matches: []string{"logs/deep/error.log", "logs/error.log", "logs/important/b.log"}},
	{patterns: []string{"*-out"}, matches: []string{"build-out/a.js"}},
	{patterns: []string{"cache-*"}, matches: []string{"src/cache-x/f.ts"}},
	{patterns: []string{"*.d.ts"}, matches: []string{"a.d.ts", "src/a.d.ts"}},
	{patterns: []string{"*.test.ts"}, matches: []string{"foo.test.ts", "src/foo.test.ts"}},
	{patterns: []string{"?.ts"}, matches: []string{"a.ts", "a/b/c.ts", "a/c.ts", "a/x/b/c.ts", "a/x/y/b/z/c.ts", "deep/nested/c.ts", "src/__tests__/a.ts", "src/a.ts", "src/cache-x/f.ts", "src/nested/deep/a.ts"}},
	{patterns: []string{"[ab].ts"}, matches: []string{"a.ts", "src/__tests__/a.ts", "src/a.ts", "src/nested/deep/a.ts"}},
	{patterns: []string{"[!a]*.ts"}, matches: []string{".hidden.ts", "a/b/c.ts", "a/c.ts", "a/x/b/c.ts", "a/x/y/b/z/c.ts", "deep/nested/c.ts", "file-name.ts", "foo.test.ts", "index.ts", "src/!bang.ts", "src/cache-x/f.ts", "src/components/Button.ts", "src/foo.test.ts", "src/index.ts", "src/nested/deep/index.ts", "src/nested/index.ts", "src/useSearch/common.ts", "src/useThing.ts", "src/vendor/lib.ts", "useThing.ts"}},
	{patterns: []string{"a.*"}, matches: []string{"a.d.ts", "a.ts", "a.tsx", "build-out/a.js", "src/__tests__/a.ts", "src/a.d.ts", "src/a.ts", "src/a.tsx", "src/nested/deep/a.ts"}},
	{patterns: []string{"src/*.ts"}, matches: []string{"src/!bang.ts", "src/a.d.ts", "src/a.ts", "src/foo.test.ts", "src/index.ts", "src/useThing.ts"}},
	{patterns: []string{"src/*"}, matches: []string{"src/!bang.ts", "src/Button.stories.tsx", "src/__tests__/a.ts", "src/a.d.ts", "src/a.ts", "src/a.tsx", "src/cache-x/f.ts", "src/components/Button.ts", "src/foo.test.ts", "src/index.ts", "src/nested/deep/a.ts", "src/nested/deep/index.ts", "src/nested/index.ts", "src/pages/admin/dash.tsx", "src/pages/index.tsx", "src/useSearch/common.ts", "src/useThing.ts", "src/vendor/lib.ts"}},
	{patterns: []string{"src/a.ts"}, matches: []string{"src/a.ts"}},
	{patterns: []string{"mm/*/b"}, matches: []string{"mm/x/b"}},
	{patterns: []string{"src/*/index.ts"}, matches: []string{"src/nested/index.ts"}},
	{patterns: []string{"/src/a.ts"}, matches: []string{"src/a.ts"}},
	{patterns: []string{"/dist"}, matches: []string{"dist/app.js", "dist/manifest.json", "dist/public/app.js"}},
	{patterns: []string{"/*.ts"}, matches: []string{".hidden.ts", "a.d.ts", "a.ts", "file-name.ts", "foo.test.ts", "index.ts", "useThing.ts"}},
	{patterns: []string{"dist/"}, matches: []string{"dist/app.js", "dist/manifest.json", "dist/public/app.js", "sub/dist/app.js"}},
	{patterns: []string{"logs/"}, matches: []string{"logs/deep/error.log", "logs/error.log", "logs/important/b.log"}},
	{patterns: []string{"node_modules/"}, matches: []string{"node_modules/react/index.js", "pkg/node_modules/x/i.js"}},
	{patterns: []string{"src/vendor/"}, matches: []string{"src/vendor/lib.ts"}},
	{patterns: []string{"**/*.ts"}, matches: []string{".hidden.ts", "a.d.ts", "a.ts", "a/b/c.ts", "a/c.ts", "a/x/b/c.ts", "a/x/y/b/z/c.ts", "deep/nested/c.ts", "file-name.ts", "foo.test.ts", "index.ts", "src/!bang.ts", "src/__tests__/a.ts", "src/a.d.ts", "src/a.ts", "src/cache-x/f.ts", "src/components/Button.ts", "src/foo.test.ts", "src/index.ts", "src/nested/deep/a.ts", "src/nested/deep/index.ts", "src/nested/index.ts", "src/useSearch/common.ts", "src/useThing.ts", "src/vendor/lib.ts", "useThing.ts"}},
	{patterns: []string{"**/*.log"}, matches: []string{"deep/nested/x.log", "logs/deep/error.log", "logs/error.log", "logs/important/b.log", "server.log"}},
	{patterns: []string{"**/index.ts"}, matches: []string{"index.ts", "src/index.ts", "src/nested/deep/index.ts", "src/nested/index.ts"}},
	{patterns: []string{"**/use*.ts"}, matches: []string{"src/useThing.ts", "useThing.ts"}},
	{patterns: []string{"**/__tests__/**"}, matches: []string{"src/__tests__/a.ts"}},
	{patterns: []string{"**/node_modules/**"}, matches: []string{"node_modules/react/index.js", "pkg/node_modules/x/i.js"}},
	{patterns: []string{"src/**"}, matches: []string{"src/!bang.ts", "src/Button.stories.tsx", "src/__tests__/a.ts", "src/a.d.ts", "src/a.ts", "src/a.tsx", "src/cache-x/f.ts", "src/components/Button.ts", "src/foo.test.ts", "src/index.ts", "src/nested/deep/a.ts", "src/nested/deep/index.ts", "src/nested/index.ts", "src/pages/admin/dash.tsx", "src/pages/index.tsx", "src/useSearch/common.ts", "src/useThing.ts", "src/vendor/lib.ts"}},
	{patterns: []string{"src/**/*.ts"}, matches: []string{"src/!bang.ts", "src/__tests__/a.ts", "src/a.d.ts", "src/a.ts", "src/cache-x/f.ts", "src/components/Button.ts", "src/foo.test.ts", "src/index.ts", "src/nested/deep/a.ts", "src/nested/deep/index.ts", "src/nested/index.ts", "src/useSearch/common.ts", "src/useThing.ts", "src/vendor/lib.ts"}},
	{patterns: []string{"src/**/*"}, matches: []string{"src/!bang.ts", "src/Button.stories.tsx", "src/__tests__/a.ts", "src/a.d.ts", "src/a.ts", "src/a.tsx", "src/cache-x/f.ts", "src/components/Button.ts", "src/foo.test.ts", "src/index.ts", "src/nested/deep/a.ts", "src/nested/deep/index.ts", "src/nested/index.ts", "src/pages/admin/dash.tsx", "src/pages/index.tsx", "src/useSearch/common.ts", "src/useThing.ts", "src/vendor/lib.ts"}},
	{patterns: []string{"src/**/index.ts"}, matches: []string{"src/index.ts", "src/nested/deep/index.ts", "src/nested/index.ts"}},
	{patterns: []string{"src/**/*.ts*"}, matches: []string{"src/!bang.ts", "src/Button.stories.tsx", "src/__tests__/a.ts", "src/a.d.ts", "src/a.ts", "src/a.tsx", "src/cache-x/f.ts", "src/components/Button.ts", "src/foo.test.ts", "src/index.ts", "src/nested/deep/a.ts", "src/nested/deep/index.ts", "src/nested/index.ts", "src/pages/admin/dash.tsx", "src/pages/index.tsx", "src/useSearch/common.ts", "src/useThing.ts", "src/vendor/lib.ts"}},
	{patterns: []string{"dist/**"}, matches: []string{"dist/app.js", "dist/manifest.json", "dist/public/app.js"}},
	{patterns: []string{"mm/**/b"}, matches: []string{"mm/b", "mm/x/b", "mm/x/y/b"}},
	{patterns: []string{"a/**/b/**/c.ts"}, matches: []string{"a/b/c.ts", "a/x/b/c.ts", "a/x/y/b/z/c.ts"}},
	{patterns: []string{"src/pages/**/*.ts*"}, matches: []string{"src/pages/admin/dash.tsx", "src/pages/index.tsx"}},
	{patterns: []string{"**/*.stories.tsx"}, matches: []string{"Button.stories.tsx", "src/Button.stories.tsx"}},
	{patterns: []string{"src/**/*.stories.tsx"}, matches: []string{"src/Button.stories.tsx"}},
	{patterns: []string{"**/*.[jt]s"}, matches: []string{".hidden.ts", "a.d.ts", "a.ts", "a/b/c.ts", "a/c.ts", "a/x/b/c.ts", "a/x/y/b/z/c.ts", "build-out/a.js", "build/keep/y.js", "build/x.js", "deep/nested/c.ts", "dist/app.js", "dist/public/app.js", "file-name.ts", "foo.test.ts", "index.ts", "node_modules/react/index.js", "pkg/node_modules/x/i.js", "src/!bang.ts", "src/__tests__/a.ts", "src/a.d.ts", "src/a.ts", "src/cache-x/f.ts", "src/components/Button.ts", "src/foo.test.ts", "src/index.ts", "src/nested/deep/a.ts", "src/nested/deep/index.ts", "src/nested/index.ts", "src/useSearch/common.ts", "src/useThing.ts", "src/vendor/lib.ts", "sub/dist/app.js", "useThing.ts"}},
	{patterns: []string{"a\\.ts"}, matches: []string{"a.ts", "src/__tests__/a.ts", "src/a.ts", "src/nested/deep/a.ts"}},
	{patterns: []string{"**/a?ts"}, matches: []string{"a.ts", "src/__tests__/a.ts", "src/a.ts", "src/nested/deep/a.ts"}},
	{patterns: []string{"src/nested/**"}, matches: []string{"src/nested/deep/a.ts", "src/nested/deep/index.ts", "src/nested/index.ts"}},
	{patterns: []string{"src/nested/**/*.ts"}, matches: []string{"src/nested/deep/a.ts", "src/nested/deep/index.ts", "src/nested/index.ts"}},
	{patterns: []string{"**/deep/**"}, matches: []string{"deep/nested/c.ts", "deep/nested/x.log", "logs/deep/error.log", "src/nested/deep/a.ts", "src/nested/deep/index.ts"}},
	{patterns: []string{"src/**/deep/**"}, matches: []string{"src/nested/deep/a.ts", "src/nested/deep/index.ts"}},
	{patterns: []string{"dist/**", "!dist/manifest.json"}, desc: "negation re-includes a file", matches: []string{"dist/app.js", "dist/public/app.js"}},
	{patterns: []string{"src/**", "!src/vendor/**"}, desc: "negation cannot re-include under an excluded directory", matches: []string{"src/!bang.ts", "src/Button.stories.tsx", "src/__tests__/a.ts", "src/a.d.ts", "src/a.ts", "src/a.tsx", "src/cache-x/f.ts", "src/components/Button.ts", "src/foo.test.ts", "src/index.ts", "src/nested/deep/a.ts", "src/nested/deep/index.ts", "src/nested/index.ts", "src/pages/admin/dash.tsx", "src/pages/index.tsx", "src/useSearch/common.ts", "src/useThing.ts", "src/vendor/lib.ts"}},
	{patterns: []string{"*.ts", "!src/a.ts"}, desc: "negation against a no-slash wildcard", matches: []string{".hidden.ts", "a.d.ts", "a.ts", "a/b/c.ts", "a/c.ts", "a/x/b/c.ts", "a/x/y/b/z/c.ts", "deep/nested/c.ts", "file-name.ts", "foo.test.ts", "index.ts", "src/!bang.ts", "src/__tests__/a.ts", "src/a.d.ts", "src/cache-x/f.ts", "src/components/Button.ts", "src/foo.test.ts", "src/index.ts", "src/nested/deep/a.ts", "src/nested/deep/index.ts", "src/nested/index.ts", "src/useSearch/common.ts", "src/useThing.ts", "src/vendor/lib.ts", "useThing.ts"}},
	{patterns: []string{"logs/", "!logs/deep/error.log"}, desc: "negation under a directory pattern", matches: []string{"logs/deep/error.log", "logs/error.log", "logs/important/b.log"}},
	{patterns: []string{"**/*.ts", "!**/*.d.ts"}, desc: "negation with double star", matches: []string{".hidden.ts", "a.ts", "a/b/c.ts", "a/c.ts", "a/x/b/c.ts", "a/x/y/b/z/c.ts", "deep/nested/c.ts", "file-name.ts", "foo.test.ts", "index.ts", "src/!bang.ts", "src/__tests__/a.ts", "src/a.ts", "src/cache-x/f.ts", "src/components/Button.ts", "src/foo.test.ts", "src/index.ts", "src/nested/deep/a.ts", "src/nested/deep/index.ts", "src/nested/index.ts", "src/useSearch/common.ts", "src/useThing.ts", "src/vendor/lib.ts", "useThing.ts"}},
	{patterns: []string{"/dist/**", "!/dist/public/**"}, desc: "anchored negation under an excluded directory", matches: []string{"dist/app.js", "dist/manifest.json", "dist/public/app.js"}},
	{patterns: []string{"!src/a.ts", "*.ts"}, desc: "later positive overrides an earlier negation", matches: []string{".hidden.ts", "a.d.ts", "a.ts", "a/b/c.ts", "a/c.ts", "a/x/b/c.ts", "a/x/y/b/z/c.ts", "deep/nested/c.ts", "file-name.ts", "foo.test.ts", "index.ts", "src/!bang.ts", "src/__tests__/a.ts", "src/a.d.ts", "src/a.ts", "src/cache-x/f.ts", "src/components/Button.ts", "src/foo.test.ts", "src/index.ts", "src/nested/deep/a.ts", "src/nested/deep/index.ts", "src/nested/index.ts", "src/useSearch/common.ts", "src/useThing.ts", "src/vendor/lib.ts", "useThing.ts"}},
	{patterns: []string{"*.ts", "!src/a.ts", "src/a.ts"}, desc: "later positive overrides an earlier negation again", matches: []string{".hidden.ts", "a.d.ts", "a.ts", "a/b/c.ts", "a/c.ts", "a/x/b/c.ts", "a/x/y/b/z/c.ts", "deep/nested/c.ts", "file-name.ts", "foo.test.ts", "index.ts", "src/!bang.ts", "src/__tests__/a.ts", "src/a.d.ts", "src/a.ts", "src/cache-x/f.ts", "src/components/Button.ts", "src/foo.test.ts", "src/index.ts", "src/nested/deep/a.ts", "src/nested/deep/index.ts", "src/nested/index.ts", "src/useSearch/common.ts", "src/useThing.ts", "src/vendor/lib.ts", "useThing.ts"}},
	{patterns: []string{"!**/*.d.ts", "**/*.ts"}, desc: "later double-star positive overrides earlier negation", matches: []string{".hidden.ts", "a.d.ts", "a.ts", "a/b/c.ts", "a/c.ts", "a/x/b/c.ts", "a/x/y/b/z/c.ts", "deep/nested/c.ts", "file-name.ts", "foo.test.ts", "index.ts", "src/!bang.ts", "src/__tests__/a.ts", "src/a.d.ts", "src/a.ts", "src/cache-x/f.ts", "src/components/Button.ts", "src/foo.test.ts", "src/index.ts", "src/nested/deep/a.ts", "src/nested/deep/index.ts", "src/nested/index.ts", "src/useSearch/common.ts", "src/useThing.ts", "src/vendor/lib.ts", "useThing.ts"}},
	{patterns: []string{"dist/**", "!dist/**"}, desc: "trailing negation cancels the whole positive", matches: []string{}},
	{patterns: []string{"a/**", "b/**", "!a/skip/**"}, desc: "negation applies only to its own subtree", matches: []string{"a/b/c.ts", "a/c.ts", "a/x/b/c.ts", "a/x/y/b/z/c.ts"}},
	{patterns: []string{"*.log", "!server.log", "*.log"}, desc: "a later positive re-excludes what a negation re-included", matches: []string{"deep/nested/x.log", "logs/deep/error.log", "logs/error.log", "logs/important/b.log", "server.log"}},
	{patterns: []string{"*.log", "!*.log", "*.log"}, desc: "alternating positive/negation, last one wins", matches: []string{"deep/nested/x.log", "logs/deep/error.log", "logs/error.log", "logs/important/b.log", "server.log"}},
	{patterns: []string{"**", "!*.ts"}, desc: "negation only reaches paths whose parent directory is not excluded", matches: []string{"Button.stories.tsx", "a.tsx", "a/b/c.ts", "a/c.ts", "a/x/b/c.ts", "a/x/y/b/z/c.ts", "boot", "build-out/a.js", "build/keep/y.js", "build/x.js", "deep/nested/c.ts", "deep/nested/x.log", "dist/app.js", "dist/manifest.json", "dist/public/app.js", "docs/readme.md", "logs/deep/error.log", "logs/error.log", "logs/important/b.log", "mm/b", "mm/x/b", "mm/x/y/b", "node_modules/react/index.js", "pkg/node_modules/x/i.js", "readme.md", "server.log", "src/!bang.ts", "src/Button.stories.tsx", "src/__tests__/a.ts", "src/a.d.ts", "src/a.ts", "src/a.tsx", "src/cache-x/f.ts", "src/components/Button.ts", "src/foo.test.ts", "src/index.ts", "src/nested/deep/a.ts", "src/nested/deep/index.ts", "src/nested/index.ts", "src/pages/admin/dash.tsx", "src/pages/index.tsx", "src/useSearch/common.ts", "src/useThing.ts", "src/vendor/lib.ts", "sub/boot", "sub/dist/app.js"}},
	{patterns: []string{"**", "!src/**"}, desc: "negation cannot re-include anything under an excluded tree", matches: []string{".hidden.ts", "Button.stories.tsx", "a.d.ts", "a.ts", "a.tsx", "a/b/c.ts", "a/c.ts", "a/x/b/c.ts", "a/x/y/b/z/c.ts", "boot", "build-out/a.js", "build/keep/y.js", "build/x.js", "deep/nested/c.ts", "deep/nested/x.log", "dist/app.js", "dist/manifest.json", "dist/public/app.js", "docs/readme.md", "file-name.ts", "foo.test.ts", "index.ts", "logs/deep/error.log", "logs/error.log", "logs/important/b.log", "mm/b", "mm/x/b", "mm/x/y/b", "node_modules/react/index.js", "pkg/node_modules/x/i.js", "readme.md", "server.log", "src/!bang.ts", "src/Button.stories.tsx", "src/__tests__/a.ts", "src/a.d.ts", "src/a.ts", "src/a.tsx", "src/cache-x/f.ts", "src/components/Button.ts", "src/foo.test.ts", "src/index.ts", "src/nested/deep/a.ts", "src/nested/deep/index.ts", "src/nested/index.ts", "src/pages/admin/dash.tsx", "src/pages/index.tsx", "src/useSearch/common.ts", "src/useThing.ts", "src/vendor/lib.ts", "sub/boot", "sub/dist/app.js", "useThing.ts"}},
	{patterns: []string{"src/**", "!src/*.ts"}, desc: "partial re-inclusion: direct children only, nested stay excluded", matches: []string{"src/Button.stories.tsx", "src/__tests__/a.ts", "src/a.tsx", "src/cache-x/f.ts", "src/components/Button.ts", "src/nested/deep/a.ts", "src/nested/deep/index.ts", "src/nested/index.ts", "src/pages/admin/dash.tsx", "src/pages/index.tsx", "src/useSearch/common.ts", "src/vendor/lib.ts"}},
	{patterns: []string{"**/*.ts", "!**/*.d.ts", "!src/vendor/**"}, desc: "several negations applying to different subsets", matches: []string{".hidden.ts", "a.ts", "a/b/c.ts", "a/c.ts", "a/x/b/c.ts", "a/x/y/b/z/c.ts", "deep/nested/c.ts", "file-name.ts", "foo.test.ts", "index.ts", "src/!bang.ts", "src/__tests__/a.ts", "src/a.ts", "src/cache-x/f.ts", "src/components/Button.ts", "src/foo.test.ts", "src/index.ts", "src/nested/deep/a.ts", "src/nested/deep/index.ts", "src/nested/index.ts", "src/useSearch/common.ts", "src/useThing.ts", "useThing.ts"}},
	{patterns: []string{"src/*", "!src/vendor"}, desc: "re-including a directory re-includes its contents", matches: []string{"src/!bang.ts", "src/Button.stories.tsx", "src/__tests__/a.ts", "src/a.d.ts", "src/a.ts", "src/a.tsx", "src/cache-x/f.ts", "src/components/Button.ts", "src/foo.test.ts", "src/index.ts", "src/nested/deep/a.ts", "src/nested/deep/index.ts", "src/nested/index.ts", "src/pages/admin/dash.tsx", "src/pages/index.tsx", "src/useSearch/common.ts", "src/useThing.ts"}},
	{patterns: []string{"dist/**", "!dist/public"}, desc: "re-including a directory does NOT help when contents match directly", matches: []string{"dist/app.js", "dist/manifest.json", "dist/public/app.js"}},
	{patterns: []string{"logs/**", "!logs/important/**"}, desc: "negation under a directory excluded by /**", matches: []string{"logs/deep/error.log", "logs/error.log", "logs/important/b.log"}},
	{patterns: []string{"docs/**", "!docs/**"}, desc: "a trailing negation cancels the whole positive", matches: []string{}},
	{patterns: []string{"!*.log"}, desc: "a set of only negations matches nothing", matches: []string{}},
	{patterns: []string{"\\!bang.ts"}, desc: "escaped leading bang is a literal filename, not a negation", matches: []string{"src/!bang.ts"}},
}

// Paths used by the scoped cases; the pattern root is "apps/web".
var gitignoreScopedPaths = []string{
	"apps/web/api/f.ts",
	"apps/web/src/a.ts",
	"apps/web/src/deep/b.ts",
	"apps/web/x.test.ts",
	"apps/web/node_modules/p/i.js",
	"apps/web/dist/out.js",
	"apps/mobile/api/f.ts",
	"apps/mobile/src/a.ts",
	"apps/mobile/src/deep/b.ts",
	"apps/mobile/x.test.ts",
	"apps/mobile/node_modules/p/i.js",
	"packages/ui/api/f.ts",
	"root.ts",
}

var gitignoreScopedCases = []gitignoreParityCase{
	{patterns: []string{"api"}, matches: []string{"apps/web/api/f.ts"}},
	{patterns: []string{"/api"}, matches: []string{"apps/web/api/f.ts"}},
	{patterns: []string{"api/"}, matches: []string{"apps/web/api/f.ts"}},
	{patterns: []string{"**/api/**"}, matches: []string{"apps/web/api/f.ts"}},
	{patterns: []string{"api/**"}, matches: []string{"apps/web/api/f.ts"}},
	{patterns: []string{"src/**"}, matches: []string{"apps/web/src/a.ts", "apps/web/src/deep/b.ts"}},
	{patterns: []string{"src/*"}, matches: []string{"apps/web/src/a.ts", "apps/web/src/deep/b.ts"}},
	{patterns: []string{"/src/a.ts"}, matches: []string{"apps/web/src/a.ts"}},
	{patterns: []string{"*.ts"}, matches: []string{"apps/web/api/f.ts", "apps/web/src/a.ts", "apps/web/src/deep/b.ts", "apps/web/x.test.ts"}},
	{patterns: []string{"**/*.test.*"}, matches: []string{"apps/web/x.test.ts"}},
	{patterns: []string{"node_modules"}, matches: []string{"apps/web/node_modules/p/i.js"}},
	{patterns: []string{"dist/**"}, matches: []string{"apps/web/dist/out.js"}},
	{patterns: []string{"deep"}, matches: []string{"apps/web/src/deep/b.ts"}},
	{patterns: []string{"**/deep/**"}, matches: []string{"apps/web/src/deep/b.ts"}},
}

// TestGitignoreParityScoped covers patterns rooted at a workspace rather than the repo
// root. Ground truth comes from a .gitignore placed in apps/web/ - git roots such a
// file's patterns at its own directory and never applies them to a sibling, which is
// exactly the scoping rev-dep gives a workspace.
func TestGitignoreParityScoped(t *testing.T) {
	const repo = "/repo/"
	const patternRoot = repo + "apps/web"
	for _, tc := range gitignoreScopedCases {
		t.Run(tc.patterns[0], func(t *testing.T) {
			want := map[string]bool{}
			for _, m := range tc.matches {
				want[m] = true
			}
			matchers := CreateGlobMatchers(tc.patterns, patternRoot)
			for _, p := range gitignoreScopedPaths {
				got := MatchesAnyGlobMatcher(repo+p, matchers, debug)
				if got != want[p] {
					t.Errorf("pattern %q rooted at %q vs %q: got match=%v, git says %v",
						tc.patterns[0], patternRoot, p, got, want[p])
				}
			}
		})
	}
}

func TestGitignoreParity(t *testing.T) {
	const root = "/repo/"
	for _, tc := range gitignoreParityCases {
		name := tc.desc
		if name == "" {
			name = tc.patterns[0]
		}
		t.Run(name, func(t *testing.T) {
			want := map[string]bool{}
			for _, m := range tc.matches {
				want[m] = true
			}
			matchers := CreateGlobMatchers(tc.patterns, root)
			for _, p := range gitignoreParityPaths {
				got := MatchesAnyGlobMatcher(root+p, matchers, debug)
				if got != want[p] {
					t.Errorf("patterns %v vs %q: got match=%v, git says %v", tc.patterns, p, got, want[p])
				}
			}
		})
	}
}
